version: '3.8'
services:
    service:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 5173:5173
        volumes:
            - .:/app/frontend
        restart: unless-stopped