export enum ENUM_USER_STATUS_CODE_ERROR {
    USER_NOT_FOUND_ERROR = 404,
    USER_EXISTS_ERROR = 409,
    USER_IS_INACTIVE_ERROR = 5402,
    USER_EMAIL_EXIST_ERROR = 409,
    USER_MOBILE_NUMBER_EXIST_ERROR = 409,
    USER_ACTIVE_ERROR = 5405,
    USER_PASSWORD_NOT_MATCH_ERROR = 401,
    USER_PASSWORD_NEW_MUST_DIFFERENCE_ERROR = 5407,
    USER_PASSWORD_EXPIRED_ERROR = 401,
    USER_VERIFICATION_TIME_EXCEED = 401,
    USER_INVALID_LOGIN = 401,
}

export enum ENUM_USER_STATUS_CODE_SUCCESS {
    USER_LOGIN_SUCCESS = 200,
}
