export const latestBlogList = [
  {
    image: '/components/particles/images/blogs/overview/latest-blog-1.jpg',
    title: 'The importance of work-life balance',
    writer: 'Leslie Alexander',
    views: '3',
    publishDate: 'Nov 3, 2022',
    viewLink: 'https://talentpoint.io/blogs/work-life-balance',
    published: false,
  },
  {
    image: '/components/particles/images/blogs/overview/latest-blog-2.jpg',
    title: 'The importance of work-life balance',
    writer: 'Leslie Alexander',
    views: '3',
    publishDate: 'Nov 3, 2022',
    viewLink: 'https://talentpoint.io/blogs/work-life-balance',
    published: false,
  },
  {
    image: '/components/particles/images/blogs/overview/latest-blog-3.jpg',
    title: 'The importance of work-life balance',
    writer: 'Leslie Alexander',
    views: '3',
    publishDate: 'Nov 3, 2022',
    viewLink: 'https://talentpoint.io/blogs/work-life-balance',
    published: true,
  },
  {
    image: '/components/particles/images/blogs/overview/latest-blog-4.jpg',
    title: 'The importance of work-life balance',
    writer: 'Leslie Alexander',
    views: '3',
    publishDate: 'Nov 3, 2022',
    viewLink: 'https://talentpoint.io/blogs/work-life-balance',
    published: true,
  },
  {
    image: '/components/particles/images/blogs/overview/latest-blog-5.jpg',
    title: 'The importance of work-life balance',
    writer: 'Leslie Alexander',
    views: '3',
    publishDate: 'Nov 3, 2022',
    viewLink: 'https://talentpoint.io/blogs/work-life-balance',
    published: true,
  },
];
